# fly.toml app configuration file generated for pa-sparet-proxy on 2023-11-04T22:23:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pa-sparet-proxy"
primary_region = "arn"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
